# Site settings
title: LZ read & study in time
SEOTitle: LZFH的博客 | LZFH's Blog
header-img: img/post-bg-desk.jpg
email: 920824835@qq@.com
description: "waiting."
keyword: "LZFH的博客, LZFH's Blog,Linux, network, C"
url: "https://cclinuxer.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lzfh2510/cclinuxer.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "waiting."
sidebar-avatar: /img/blog.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: false
# weibo_username:     waiting
zhihu_username:     wait
github_username:    lzfh2510
#twitter_username:   waiting


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: /:year/:month/:title/
paginate: 18
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: cclinuxer

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 3563f5d8e5a9570dd67c                            #生成的clientID
  clientSecret: edfc012d562702c9747b9abc0b36c2400e8b6fa1    #生成的clientSecret
  repo: cclinuxer.github.io    #仓库名称
  owner: cclinuxer    #github用户名
  admin: cclinuxer
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计
# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
service-worker: true


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Jeffxie",
        href: "https://x-lugoo.github.io/"
    },{
        title: "Quentin Schulz",
        href: "https://github.com/QSchulz"
    },{
        title: "Ilya V. Matveychikov",
        href: "https://github.com/milabs"
    },{
        title: "Oliver Yang",
        href: "http://oliveryang.net/"
    },{
        title: "蜗窝科技",
        href: "http://www.wowotech.net/"
    },{
        title: "Linux Performance",
        href: "http://linuxperf.com/"
    },{
        title: "魅族内核团队",
        href: "http://kernel.meizu.com/"
    },{
        title: "dog250",
        href: "https://me.csdn.net/blog/dog250"
    },{
        title: "网络分析",
        href: "https://me.csdn.net/fanxiaoyu321"
    },{
        title: "lwn",
        href: "https://lwn.net/Kernel/"
    },{
        title: "tolimit",
        href: "https://www.cnblogs.com/tolimit/"
    },{
        title: "ArthurChiao",
        href: "http://arthurchiao.art/articles-zh/"
    },{
        title: "jeff xie",
        href: "https://cloud.tencent.com/developer/user/5812642"
    },{
        title: "armlinuxww-network",
        href: "https://blog.csdn.net/armlinuxww"
    },{
        title: "zhu hui(mm)",
        href: "http://teawater.github.io/"
    },{
        title: "linux脉络梳理进程、IO、内存",
        href: "http://kernel.pursuitofcloud.org"
    },{
        title: "CMU paper",
        href: "https://www.pdl.cmu.edu/PDL-FTP/"
    },{
        title: "CLK PPT",
        href: "https://github.com/cclinuxer/CLK"
    },{
        title: "SOSP",
        href: "http://www.sosp.org/"
    }
]

theme: jekyll-theme-architect
